version: 0.0
Resources: 
  - LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "sagemaker-training-job"
        Alias: "live"
        CurrentVersion: "3"
        TargetVersion: "4"