version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies for Lambda SageMaker Training..."
      - pip install --target ./package boto3  
  build:
    commands:
      - echo "Packaging Lambda function for SageMaker training job..."
      - mkdir -p package  
      - cp -r Lambda-SageMaker-Training-Job/*.py ./package/  
      - cp Lambda-Greengrass-Creation/lambda-sagemaker-training-appspec.yml ./
      - cd package
      - zip -r ../lambda_sagemaker.zip .  
      - cd ..
artifacts:
  files:
    - lambda_sagemaker.zip  
    - lambda-sagemaker-training-appspec.yml
cache:
  paths:
    - ./package/**
