version: 0.0
Resources:
  - LambdaFunction:
      name: "lambda-greengrass-creation"
      alias: "live"
  - LambdaFunction:
      name: "greengrassLSTMFunction"
      alias: "live"
  - LambdaFunction:
      name: "sagemaker-neo-compilation-job"
      alias: "live"
  - LambdaFunction:
      name: "sagemaker-training-job"
      alias: "live"
  - LambdaFunction:
      name: "edge-healthcare-lambda"
      alias: "live"
    
