version: 0.0
Resources:
  - LambdaFunction:
      Name: "lambda-greengrass-creation"
      Alias: "live"
  - LambdaFunction:
      Name: "greengrassLSTMFunction"
      Alias: "live"
  - LambdaFunction:
      Name: "sagemaker-neo-compilation-job"
      Alias: "live"
  - LambdaFunction:
      Name: "sagemaker-training-job"
      Alias: "live"
  - LambdaFunction:
      Name: "edge-healthcare-lambda"
      Alias: "live"
    
