version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "Zipping Lambda functions without adding appspec.yml"
      - zip -r Lambda-Greengrass-Creation/greengrass_creation.zip Lambda-Greengrass-Creation/*
      - zip -r Lambda-Greengrass-LSTM/greengrass_LSTM.zip Lambda-Greengrass-LSTM/*
      - zip -r Lambda-Neo-Compilation/lambda_sagemaker_neo.zip Lambda-Neo-Compilation/*
      - zip -r Lambda-SageMaker-Training-Job/lambda_sagemaker.zip Lambda-SageMaker-Training-Job/*
      - zip -r Lambda-WebSocket/lambda_websocket.zip Lambda-WebSocket/*

artifacts:
  files:
    - Lambda-Greengrass-Creation/greengrass_creation.zip
    - Lambda-Greengrass-LSTM/greengrass_LSTM.zip
    - Lambda-Neo-Compilation/lambda_sagemaker_neo.zip
    - Lambda-SageMaker-Training-Job/lambda_sagemaker.zip
    - Lambda-WebSocket/lambda_websocket.zip
    - appspec.yml 