version: 0.0
Resources:
  - greengrassLSTMFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "greengrassLSTMFunction"
        Alias: "live"
        CurrentVersion: "3"
        TargetVersion: "4"