version: 0.0
Resources:
  - GreenGrassLSTMFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "GreenGrassLSTMFunction"
        Alias: "live"
        CurrentVersion: "3"
        TargetVersion: "4"