version: 0.2

phases:
  install:  
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies for Greengrass Lambda..."
      - pip install --target ./package greengrasssdk
      - pip install --target ./package numpy
      - pip install --target ./package tensorflow

  build:
    commands:
      - echo "Packaging Lambda function for IoT Greengrass..."
      - mkdir -p package  
      - cp -r Lambda-Greengrass-LSTM/*.py ./package/  
      - cp Lambda-Greengrass-LSTM/lambda-edge-appspec.yml ./
      - cd package 
      - zip -r ../greengrass_lstm.zip .  
      - cd .. 
      - echo "Edge Lambda package created."

artifacts:
  files:
    - greengrass_lstm.zip
    - lambda-edge-appspec.yml
cache:
  paths:
    - ./package/**
