version: 0.0
Resources: 
  - LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "edge-healthcare-lambda"
        Alias: "live"
        CurrentVersion: "2"
        TargetVersion: "3"
    