version: 0.0
Resources: 
  - LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "edge-healthcare-lambda"
        Alias: "live"
        CurrentVersion: "CURRENT_VERSION_PLACEHOLDER"
        TargetVersion: "TARGET_VERSION_PLACEHOLDER"
    