version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for Lambda Cloud"
  build:
    commands:
      - echo "Zipping Lambda Cloud function"
      - zip -r Lambda-WebSocket/lambda_websocket.zip Lambda-WebSocket/* -x Lambda-WebSocket/appspec.yml
      - mv Lambda-WebSocket/appspec.yml .
      - echo "Publishing new Lambda version"
      - NEW_VERSION=$(aws lambda publish-version --function-name edge-healthcare-lambda --query 'Version' --output text)
      - echo "Updating alias to point to new version"
      - aws lambda update-alias --function-name edge-healthcare-lambda --name live --function-version $NEW_VERSION

artifacts:
  files:
    - Lambda-WebSocket/lambda_websocket.zip
    - appspec.yml  
