version: 0.0
Resources:
  - sagemaker-neo-compilation-job:
        Type: AWS::Lambda::Function
        Properties:
          Name: "sagemaker-neo-compilation-job"
          Alias: "live"
          CurrentVersion: "3"
          TargetVersion: "4"