version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "Adding appspec.yml to the existing Lambda zip..."
      # Add appspec.yml to the existing lambda_sagemaker_neo.zip
      - - if [ -f Lambda-Neo-Compilation/lambda_sagemaker_neo.zip ]; then zip -g Lambda-Neo-Compilation/lambda_sagemaker_neo.zip Lambda-Neo-Compilation/appspec.yml; else echo "Zip file not found!"; exit 1; fi
      - echo "AppSpec file successfully added to Lambda zip."

artifacts:
  files:
    - lambda_sagemaker_neo.zip