version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies for Greengrass Lambda..."
      - pip install --target ./package boto3  
  build:
    commands:
      - echo "Packaging the Greengrass creation Lambda function..."
      - mkdir -p package  
      - cp -r Lambda-Greengrass-Creation/*.py ./package/  
      - cp Lambda-Greengrass-Creation/greengrass-creation-appspec.yml .
      - cd package
      - zip -r ../greengrass_creation_combined.zip .
      - cd ..
      - zip -g greengrass_creation_combined.zip Lambda-Greengrass-Creation/greengrass-creation-appspec.yml
      - echo "Lambda Greengrass Creation with AppSpec file created."
  post-build:
    commands:
      - echo "Uploading the combined deployment package to S3..."
      - aws s3 cp greengrass_creation_combined.zip s3://code-pipeline-artifacts-talha/greengrass_creation_combined.zip
      - echo "Upload Complete."

artifacts:
  files:
    - greengrass_creation_combined.zip  

cache:
  paths:
    - ./package/**
