version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "Adding appspec.yml to the existing Lambda zip..."
      # Add appspec.yml to the existing greengrass_creation.zip
      - if [ -f Lambda-Greengrass-Creation/greengrass_creation.zip ]; then zip -g Lambda-Greengrass-Creation/greengrass_creation.zip Lambda-Greengrass-Creation/appspec.yml; else echo "Zip file not found!"; exit 1; fi
      - echo "AppSpec file successfully added to Lambda zip."

artifacts:
  files:
    - greengrass_creation.zip